[normal]
":" = "command"
"ctrl-o" = "back"
"ctrl-i" = "forward"
"ctrl-g" = "pet-duck"
"za" = "toggle-transcript-item"
"zR" = "expand-transcript"
"zM" = "collapse-transcript"

[command]
escape = "normal"
enter = "execute-command"
